### ISSUE TITLE
测试issue讨论区

### ISSUE THREAD

**Issue by xen0n** [jnrain/issue-tracker#1]
@jnrainerds/2013-freshman 很好, 这个甚至连邮件列表都可以部分取代了 (issue和团队本身就是邮件列表), 作业就这么布置了大家没什么意见吧?

**Comment by xcodebuild** [comment]
可以的，没意见 -- 发自 Android 网易邮箱 在2013年10月13日 14:18， Wang Xuerui写道： @jnrainerds/2013-freshman 很好, 这个甚至连邮件列表都可以部分取代了 (issue和团队本身就是邮件列表), 作业就这么布置了大家没什么意见吧? — Reply to this email directly or view it on GitHub.

**Comment by xen0n** [comment]
@soulfere 这样大家都可以动起来了
