### ISSUE TITLE
如何优雅的用JQuery拼接HTML

### ISSUE THREAD

**Issue by xcodebuild** [jnrain/issue-tracker#14]
Angularjs中可以直接在HMTL中书写变量名{{}}，从而可以很直观的看懂代码含义
而JQuery在拼接代码时，究竟是采用操作DOM(看起来更符合JQuery规范，但是很不直观)还是使用HMTL字符串再sprintf的方式拼接

**Comment by xen0n** [comment]
为了你的理智（和安全性），请用类似`$('<div></div>').append($('...').text(...)).append(...)`的形式，像我之前演示那样。直接拼html碎片十分丑陋
