### ISSUE TITLE
恩，有谁能告诉我怎么在项目里新建文件夹...

### ISSUE THREAD

**Issue by dark-flame-master** [jnrain/issue-tracker#15]
热情洋溢地在网页上上传了所有文件，但是发现没有文件夹......
找了找网上的教程，都是命令行弄上去的......
难道只有全部删掉再用命令行上传这一条路了吗？

**Comment by xcodebuild** [comment]
........话说不是本地建好然后推上去的么

**Comment by xen0n** [comment]
请用命令行... 先 `git clone` 下来你现在的状态, 然后 `mkdir` 建目录, `git mv` 移动文件进去, `git commit` 提交, `git push` 推上去

**Comment by dark-flame-master** [comment]
好吧，我早该觉悟......
谢谢热情解答。
关了这个issue吧

**Comment by xen0n** [comment]
自己关呗~

**Comment by xen0n** [comment]
卧槽最后这issue还是没关上●﹏●

closing
