### ISSUE TITLE
前后端分离有什么缺点么，为什么没有广泛使用

### ISSUE THREAD

**Issue by xcodebuild** [jnrain/issue-tracker#16]
第一次培训就说道前后端的分离(前端通过ajax向后端请求JSON)，我也感觉到这种方式的很多优点，但是为什么他们没有在各个知名网站广泛使用(包括Github本身)。  
之前还看到一些由Python写的Blog,采用了一种templet的方法，最后仍然是后端生成静态特面。他们为什么没有采用那种前端和后端完全分开的方式。

**Comment by xen0n** [comment]
缺点的话主要还是对JS的必须依赖关系，这种网站如果浏览器不能JS的话是完全不能使用的。我以前也想过这一点所以前几版的新站重写并没有用这种思路，不过后来马上就发现这样会导致后端前端两套重复的模板代码，不干净。其他的我想起来再说，在吃饭。。。
