### ISSUE TITLE
怎么在使用<select>时读取被选择的<option>的value

### ISSUE THREAD

**Issue by sunemperor** [jnrain/issue-tracker#18]
发现在移动端使用<select>的界面高大上，真心想用，结果鼓捣了半天也没懂在js里怎么读取对应选择的<option>的value，求指教～

**Comment by soulfere** [comment]
你就是听雨上站内我的那位安卓开发者吧？

**Comment by sunemperor** [comment]
？
欸……我只是开发关于江大地图的网页的

**Comment by xen0n** [comment]
哦，http://lmgtfy.com/?q=jquery+select+value

// 汉语的话，百度 `jquery select 值` 也有答案。你别跟我说你现在还没用jQuery啊。。。

**Comment by sunemperor** [comment]
只是看着jquary略微有点不爽罢了，大丈夫だ

**Comment by xen0n** [comment]
额. 这样啊...

那最后有没有用jQuery? 我跟你说跨浏览器开发不用库就是自找罪受... 你会懂的... 然后没问题了你可以自己把issue给close了, 嗯

**Comment by sunemperor** [comment]
最后还是用了个略麻烦的方法，不过效果一样，这就关
