### ISSUE TITLE
Android Studio vs Eclipse

### ISSUE THREAD

**Issue by xcodebuild** [jnrain/issue-tracker#19]
Google新发布的Android Studio对于项目的构建是基于Gradle，那么未来听雨的安卓项目会不会脱离Eclipse，以及，我们还要学习Maven么(Gradle vs Maven?)。@xen0n

**Comment by xen0n** [comment]
> Google新发布的Android Studio对于项目的构建是基于Gradle，那么未来听雨的安卓项目会不会脱离Eclipse，以及，我们还要学习Maven么(Gradle vs Maven?)。@xen0n

等到Android Studio使用再广泛一点吧... 我反正现在暂时没有跟进, 主要是前段时间精力有限.
Maven的话你自己不写库什么的就只要了解最基本的依赖关系指定和解析就行了
