### ISSUE TITLE
听雨安卓0.4发布公关

### ISSUE THREAD

**Issue by xen0n** [jnrain/issue-tracker#2]
@jnrainerds :

现在0.4已经发布到更新频道, 0.3用户会收到升级提示, 但还没有进行任何媒体覆盖.

大家一起讨论下以下一些主题吧:
-   宣传材料的收集和撰写
  
  这个不一定只局限在之前的ChangeLog风格, 要让没用过的人也知道我们有什么. 为此我们需要一些截图之类的材料, 需要有人准备. 还有我不会写那种一般人能看懂的发布说明文字, 但我们需要一些适度的宣传材料, 单纯罗列技术进步的话小白们是看不懂的. 这个也要有人做
-   进站宣传设计
-   顺便加入一些招人的材料

大家觉得有什么遗漏的也可以随意补充.

**Comment by ryanaltair** [comment]
有同学问我 检测更新的设置在哪里

**Comment by xen0n** [comment]
偏好设置里可以看到... 在登录界面的话按菜单键也可以进设置界面

话说跑题讨论请学会开单独issue... 像这个就最好发到jnrain-android的issue里, 这次算了以后要注意哦

**Comment by ryanaltair** [comment]
好的 其实觉得是和0.4的更新有关 好的 以后会注意的

**Comment by soulfere** [comment]
进站那方面我去协调，还有就是进站的原来放置0.3的那个位置换成0.4要怎么换？

**Comment by xen0n** [comment]
这个现在比较坑，只能直接往听雨SVN版本库推。。。我一直没时间改那个进站管理脚本。其实现在是想在页面右上角（吧）悬浮一个半透明固定模块了，面积大一点 (比如170x300)

**Comment by xen0n** [comment]
@soulfere 进站banner更换完毕, 不过依然建议做一个悬浮模块. 你那里进展如何?

**Comment by soulfere** [comment]
这边的话软文正在写，准备把这边技术部小孩写的都整合起来给编辑部来发宣传软文，同时人人和微博还有微信也开始联系推信息，至于下载地址我就给进站banner那个地址了。

**Comment by xen0n** [comment]
在 2013-11-9 下午1:14，"Zhai Qiushi" notifications@github.com写道：

> 这边的话软文正在写，准备把这边技术部小孩写的都整合起来给编辑部来发宣传软文，同时人人和微博还有微信也开始联系推信息，至于下载地址我就给进站banner那个地址了。

不错嘛。。。像模像样的了。。。吾辈甚是欣慰

进站banner那个是301到实际下载地址的，这样一来URL好看，二来方便万一以后负载均衡实际地址随便换（希望能做到那种用户量吧23333）

**Comment by ryanaltair** [comment]
其实 我觉得 在新站没出来前 还是不要大范围推好
因为 很多时候 用户的第一次印象 决定了之后所有的印象 
我的建议
我们可以将这次推广作为  一次测试用户抢先体验这样的活动来进行宣传 并且 可以登记愿意作为测试用户 的人的联系方式
第一可以 收到他们的回馈 
第二 更重要的 让他们知道 他们是测试用户 那么 他们对于 他们不满意的地方 会有更高的忍耐度

**Comment by xen0n** [comment]
@soulfere @ryanaltair 嗯这个很重要... 我一直忘了说(汗

因为是KBS的后端, 有些问题 (比如频繁登陆) 用户会怪到我们头上... 必须让用户觉得这是我们在稍大范围进行测试而已, 从而不至于怀疑我们的运营能力

这一点真是多谢提醒- -!!

**Comment by xen0n** [comment]
听雨新站内测箭在弦上，听雨安卓0.x系列生命周期结束。(0.5我甚至没开始开发)

那么这个issue就close了
