### ISSUE TITLE
听雨 研发中心的 可能发展选项 （题目已改 原题 听雨 研发中心的 美工 可能发展选项）

### ISSUE THREAD

**Issue by ryanaltair** [jnrain/issue-tracker#20]
@xen0n  @jnrainerds 

为了提供一个更加灵活 更加主动的组织架构
特此开issue公开征询意见
现有3种基本设想有：
1.   在未来的研发中心中设立艺术督导 （人员构成 仅包括 大二级美工）用于帮助开发过程中的美术指导（包括但不限于 UI设计 色彩搭配 logo设计 等）
2.    在未来的研发中心中设立艺术指导组 （人员构成 包括 大一大二级美工）用于帮助开发过程中的美术指导（包括但不限于 UI设计 色彩搭配 logo设计 等）
3.    在听雨设立 设计中心（与研发中心同级），其任务包括 品牌（为所有听雨产品 活动 提供 专有logo 并 配置宣传资料 等 ） 人员构成 大一大二级美工（设计专员） 听雨研发中心的开发项目可抽调一（多）名美工（设计专员）作为艺术指导，共同完成项目开发 （ryanaltair recommended）

以上仅代表ryanaltair观点，请尽早提出意见

**Comment by xen0n** [comment]
个人倾向于设计团队位于研发中心内部, 与研发人员同级的安排, 也就是研发中心包括实习生, 工程师和设计师 (或者设计专员, 美工这个名字都可以, 都是正确的职位名). 如果觉得理解起来不方便也可以是设计中心的结构

**Comment by xen0n** [comment]
对了 @soulfere 你怎么想?

**Comment by soulfere** [comment]
这个在中层会讨论了很久了，我的想法是把研发中心划分成研发部和宣传部，美工拉到研发中心里的宣传部。因为不论是进站，logo，还是纪念品，明信片，吉祥物，都和宣传有很大的关系。

**Comment by soulfere** [comment]
研发中心专注于产品和产品推广，并行运营中心，专注运营，还有内部组织结构整理，还有品牌推广。

**Comment by ryanaltair** [comment]
对了 补充下： 我个人倾向于 
以后听雨以项目组的形式运作
 即所有听雨的活动 
都有项目组来运作（理由： 项目组运作快捷 能有效减少由于部门间分工带来的 反应缓慢 ）
  产品（包括策划 宣传 产品开发以及短期维护）
 或者
 活动 （策划 宣传 举办活动 ）等
对应的 对于 产品研发这一块 的流程
1.  提供需求 ，审核需求
2.  任务招标（研发中心 自报名 或者 指派 项目负责人 ）
3.   筹建项目组（初步 ）
4.  项目运行（产品开发）
5.  小规模内测 
6.  产品基本成型
7.  项目组扩招
8.  准备项目宣传活动
9.   宣传
10.  短期维护改进
11.  项目成型

为了显示出 不偏题
这里 主要是更加明显的 给出这样的问题 
美工 或者 说艺术指导 
应当是在 3阶段开始加入 还是说 在 7阶段加入

以及 项目扩招之后 是否需要 更换 负责人（负责活动运作 而不是 产品开发） 
或者说 需要再添加一名负责人 （负责活动运作 ） （是在初期筹建，即3 阶段 时候 加入 还是 7阶段加入）

个人觉得每个选项都有利弊

希望得到大家的意见（附带 理由）

**Comment by dark-flame-master** [comment]
我可以发个言不。。。虽然是个老帖。。
我觉得最重要的 不是 我们某个人 或者大部分人 偏好的模式是什么，而是 我们能做到哪一种。
说得直白一些，三位学长心中的美工部完全不是 干同一件事情的 同一个组织，可执行性也并不相同，我想分析一下。

产生与研发中心同级的组织，也就是部长的那个想法，其实仅仅是把美工部从线下分出去，强制拉到线上来。（本人也这么说）那么，其实和现在他们所干的事情没有多区别——如果线下有什么事，他们还是会去帮忙；而且还是同样不懂网页独特的设计，仍从原来的角度出发，仍然会产生同样的问题。
而且，把美工部拉出去线下会同意吗？谁去画海报？谁去配合编辑部那个难得一见的刊物。。。。名义上实行性大，但是基本没法解决问题。

然后是汪学长的提议——项目组（允许我如此简称）其实我比较赞同，但不是完全同意。
看起来比较完备，从项目的角度出发，提出项目，寻找负责人，寻找参与者（包括美工），进行项目，完成项目的制作，宣传执行，结束。生命周期从有项目开始到项目消亡结束————那么，请问这段时间是多久呢？
项目组的工作方式——在我看来，有一个必要因素————时间不长。太长了，组就保不住了。从这次四个项目组就可以看出来，基本上是很难使得很多人（或者说大部分人）在长期对于一个项目产生足够的热情——既没有金钱奖励、也没有惩罚措施，你让项目负责人如何去管理底下的人——如果有一个编写某应用的项目，然后持续时间要3个月，那么有些新人一开始无脑的报了，最后无责任的退出，那么怎么办？当然这可以预防，通过良好的过滤机制的话。但是，我觉得大学里的学长们普遍都对于新生抱有不切实际的妄想——而新生自己也有的话，就会有一大堆坑了。（以我自己来说，差点就成坑了---我回来还要好好学习，改进改进）改善方法可以是让项目不那么好新建，需要一些认证，比如负责人至少是大二，之前必须有多次参加项目经验；而参与者也要有足够时间，而且精力也够——纯艺术生或者很苦但和编程无关的的专业要慎招（有那种人吗？）。当然这些都是创作层面上的——汪学长是以更高的层次来看的----至于宣传推广我就不管了。
但是，之后才是我的不满。那就是这其实并没有把美工部分出去。从某种程度上来说，这可比部长的方案还要保守，甚至于一点要分的意思都没有。而我之所以强调着一点，是因为，这个分不分，意义很大。
首先不分，就没法脱离线下的俱乐部来找人--其次，看这个人员配比，估计还是要有外联和办公室啥的。。。所以基本上研发中心就还是挂名的技术部。部长的提议是争取 把 技术部提高层面，至少是名分上的， 争取 把 美工部 抢过来。但是汪学长的提议里，技术部还是技术部，而且可能地位还更低——如果负责人是办公室啥的的话。可能你们觉得是危言耸听，但如果强制进行项目化——尤其是想把美工部整进来，还让项目 必须 拥有宣传、活动等属性（原谅我把活动狭义理解为摇旗呐喊拉横幅），那么谁擅长弄那些麻烦而形式的东西，谁就能成领导——而这正是我不愿意看到的。另外说一句，现在咱们的几个项目，比起项目，任务更加合理。人数很少，无人管理（或者管理者几乎隐形），依靠个人能力很多。而成熟的项目应该很少依赖于个人的能力高低，基本上找谁去，进度都该差不多。可执行性上很高——或者说不加干预的话，很可能就这么形成了。
另外我还想说一句，如果全部项目组化，那么部这个单位就成了装人的套子了，没有更高的意义。

最后说一下站长的提议。。。
站长的提议一直是反传统、反封建的。如果跟前面两位学长一比，立刻就看出差别来了。
鉴于写的篇幅太短，不好揣测全貌，我就根据着站长的，说一下我自己的看法。

第一，不要把美工部来过来，我们要的不是美工部。

换句话说，我希望能把现有的美工部分为
1，想继续画海报啥的的人
2，想进行网页设计、产品设计的人
只要2，不要1。而且2中的人也不是全要，愿意学习些网页设计基础的才可以招，完全从想象出发，不管技术的不要（或者也可以认为他们不能更完美的运用网页的各种特质）
（就是说按照部长的计划进行的话，需要改进：不能把所有美工都拉过来。原因参照上面的回答。而进不进行再划分并不是特别重要 ）

第二，一定要划清界限！

研发中心就是研发中心，俱乐部就是俱乐部——我们可以利用他们线下活动，他们可以利用我们线上活动——不要别的接口。
首先要保证不能让外行领导内行，所以如果要实行项目制的话，也是在研发中心内部实行，设计人员是研发中心的，编程人员也是，管理人员更是。

第三，要保证研发中心招得上人......

人才流失很严重。
站长可能觉得不能坚持下去的都没有必要流，但是没必要一开始就这么严厉吧？
我觉得有三点是必需要做的：

一，建立更加紧密的个人联系。 同期之间应该有交流，而且应该不少，应该提供这样的场所和机会（至少有和没有的区别是巨大的）。如果可能的话，同专业的前辈和后辈们互相交流下， 给他们些提示和警告。（ps：站长培训是好，就是太高端，你要照顾大多数人的理解能力，或者起码提示下节课内容，让他们好预习下；不然后果很严重）

二，开始的时候要      宽     松    。一进入大学，很多同学还是抱着玩玩的心态的，在招进的新生中，也不乏有些是完全不知道将要面对什么的。这时候，首先不要让他们吓着。
举个栗子。
我建议，下次技术部招新改一下。
报名的人，最好一人带一台电脑去，然后现场教授html的技术（如果hello world太低端的话，就改成混合使用html、css、js等）这样首先能找出那些潜在的大牛---都会编了以后也好办---同样也让别的同期招进的人不感觉太自卑——基本上普通人对于那些通识是完全不知情的。如果能通过这么直接的结果让他们认识到，网页编程是那么简单（和编程语言来比的话），自己那么容易就可以做出网页，可以不再受蒙蔽。同时，一些有经验的人，也不过尔尔，和自己的差距是有，但不是难以弥合，如此如此，让他感觉自己戴上主角光环的日子近了，那么就好办了。起码把人家骗进来了。——不要一开始就要求人家有多少觉悟——觉悟和爱的大小是成正比的，不能让人家一开始就爱上个陌生人！（如果站长执意要求招入有能力的少数精英，俺也无话可说，但是社团的目的不仅仅是做出成品，让他们成长，尤其是快乐的成长，更好地学习，认识更多的人，提升自己——才是最终目的。我不太同意所有人都想当网络工程师，这就好像每个你要求每个为了泡妹子而组成的乐队最后都成明星，虽然有的确实误打误撞的成了）

三，简单。我觉得程序员应该不喜欢太复杂的机构。当然大部分人都应该不喜欢。但是，我们为了有些目的要牺牲掉简单，比如完成一个项目。程序员，最普通的程序员，应该都是不善言辞的，至少不是巧舌如簧的。他们会觉得无聊的回忆、无止境的研讨等完全没有意义——从部长开的会如此之少就可以看出——这很好。
要减少琐事——其一就是线下各种 摇旗呐喊拉横幅搬桌挪椅子开会做演讲评优选干事 。看这么长看着都烦吧。
其二就是要有明确的学习曲线和学习目标——可能的话，每个学长都跟他们研究下怎么学，去哪里学，学习速度要多少。不然就是低效的学习。

。。。。至此，不知不觉就写了很多了。多亏了敲代码，打字速度飞增，如果是原来，估计要打一天。。。
恩，就是这样，如果你能看到这，非常感谢！

**Comment by ryanaltair** [comment]
@dark-flame-master  
第一点 不要叫我 汪学长。。。 可以叫我 河鼓（ryanaltair的altair的意思即是河鼓的意思，不好意思扯题了） 或者 直接互换我真名（鉴于在github上面， 可以称呼我 琰学长 额 比较帅对吧）
第二点 感谢你的回复！集思广益！听雨拒绝个人的武断决定。

以下开始是认真的回复：
1.   再次强调 欢迎所有人加入讨论， 你们才是研发中心的核心 
2.  关于 研发中心的级别 与其他中心相比 拥有绝对的自由度，最直白的解释就是 听雨俱乐部主席 既不负责 也不领导 研发中心 （仅保留有知情权），研发中心由研发中心的人来领导 （研发中心的负责人 直接与指导老师对话） 将研发中心的级别提升，并由内行人来领导， 是听雨改组的关键
3.  关于 项目组的组成问题 ; 对于研发中心 内部孵化的各个项目， 由研发中心成员带头，计划，构建（招人），实施。这类项目包括而不限于 app，website，mobile website etc（甚至包括 hareware）对于这类项目 成员一般限于研发中心，对于其他项目 例如 听雨微信项目 听雨视频项目组 等等，由于项目本身要求，不能完全依托 研发中心，而需要听雨其他力量的加入，仅举 微信项目组 就有这么几个方面 公关联系，编辑，技术开发 等。 对应于项目组 （产品研发 类）的流程 需要注意到 美工等的加入时间 ，以及有这样一种可能性：项目初期由研发中心负责（一线），项目后期由听雨其他力量加入，研发中心人员退居二线 //这个方案 有利有弊 具体方案还没确定 可能多方案并行
4.  项目的审核问题，这个一定会有，这个事情 其实就是 听雨俱乐部主席和研发中心负责人需要做的事情（对于 研发中心内部项目 无需主席审核）
5.  我保证 研发中心成立后 研发中心成员不会再参加食堂呼啦啦活动了（当然 欢迎参与）
6.  关于报名方式 会更加灵活 由中心自主决定（推荐与听雨主体同步进行）

//听雨主体的方案仍在制定 但不管任何一种方案 研发中心的成立 是势在必行 由研发中心的人负责研发中心 也是 势在必行  

感谢阅读漫漫长贴
最后！ @jnrainerds  欢迎其他人加入讨论

**Comment by xen0n** [comment]
改标题... 改的时候请注明 `(was: <原标题>)` 否则后来的人都不知道改标题之前都在讨论啥了...

我8月份时候做过一张完整的规划, 会贴在另外的issue里, 然后reference这里, 大家都能看到, 让这个issue歇会吧...

**Comment by ryanaltair** [comment]
好的 上完课回去改 （更新 原标题 已增加）

发自我的 Windows Phone

---

发件人: Wang Xueruimailto:notifications@github.com
发送时间: ‎2013/‎12/‎17 23:39
收件人: jnrainerds/issue-trackermailto:issue-tracker@noreply.github.com
抄送: wang dongyanmailto:al_tair@live.com
主题: Re: [issue-tracker] 听雨 研发中心的 可能发展选项 （题目已改） (#20)

改标题... 改的时候请注明 `(was: <原标题>)` 否则后来的人都不知道改标题之前都在讨论啥了...

我8月份时候做过一张完整的规划, 会贴在另外的issue里, 然后reference这里, 大家都能看到, 让这个issue歇会吧...

---
