### ISSUE TITLE
怎么看京东云擎提供的类似github的服务

### ISSUE THREAD

**Issue by xcodebuild** [jnrain/issue-tracker#21]
恩我不是来做广告的，因为还没有时间去尝试看看怎么样

[京东](http://appengine.jd.com)最近也推出了类似SAE/BAE的云服务，看起来更高端了,可以通过git直接维护云端代码(这点BAE也可以)，但是他提供了类似github的[一些东西](https://code.jd.com/assad/Python-APNS-Service),这是随便搜的一个例子，现在上面的代码量少的可怜   

恩，其实我就是想问，**对于这种类似github的其他网站，我们怎么看待**，或者给个评价吧   

_顺便提醒一下不要用邮箱注册，我用gmail注册他自动生成了一个叫code.falli的用户名给我，还！不！能！改！_

**Comment by dark-flame-master** [comment]
我还上过CSDN，上面也有类似github的服务。
在一篇专访中（http://www.csdn.net/article/2013-12-03/2817679-The-journal-of-GitHub-in-China-part-one）
里面提到和github的关系，说csdn有了自己的code（https://code.csdn.net/）
首页里就有那么一个叫做“code”的分区，打开后会发现和github很类似。

恩，现在开始分析。
github在将来很难一家独大——有可能会有崇尚简单操作的人开发更简单的平台（比如做到所见即所得）
而且简单将是趋势——你觉得100年后还会有人用命令行进行开发吗？

然后是近期趋势——你可以看出来，中国不是没有，而且还是有很多——那么直接的结果，可能就是，
github被墙了！那么就只能用国内的了！不过那有点恶心，而且起码不会很快发生，况且版本库的迁移不是说改就改的。。。。。当然他们失败的几率也很大，想用他们的话风险不小。

最后说一句——我觉得中国有一天就没墙了。。。愿景

**Comment by ryanaltair** [comment]
github应该不会被墙吧（个人观点）//希望如此吧

**Comment by dark-flame-master** [comment]
我主要是想起来python的主页似乎就有一次上不了（站长说的）因为版本号里有六和四。。。。

**Comment by xen0n** [comment]
@ryanaltair GitHub之前因为12306抢票助手的事件被墙过短暂时间, 技术是SSL证书劫持, 不过后来又恢复了. 一般来说这种距离一般大众比较远的网站没有什么墙的必要, 多想想墙存在的意义是什么

@dark-flame-master 嗯, 所以有个[Alternate download page for China](http://python.org/getit/), 2333333

最后是楼主... @CodeFalling GitHub-clones多了去了, 你与其关注那些显然醉翁之意不在酒的代码托管站还不如看看[GitCafe](https://gitcafe.com/)这个国人 (ghosTM55) 制作的真正中国化GitHub clone呢... 参考
- Facebook - 从网
- Twitter - XX微博
- StackOverflow - SegmentFault (09年那一阵子有过一个Segfault, 不过是个美国站吧好像, 内容完全不相关. 然后当时服务器硬盘损坏数据不可恢复, 站就倒了. 具体可维基)
- Quora - 知乎
- Pinterest - 堆糖 (?, 现在已经有了自己的风格, 不过主题思想都是图片分享)
- 点点点

所以与其去关注"哇XX公司做了个山寨XX网站耶"还不如多想想那家公司到底是想干啥= =

// EDIT: 加上了StackOverflow的对比

**Comment by xen0n** [comment]
诶对, 为了防止你们问我"为什么有GitCafe这个汉语站还要我们学英语上GitHub"这个问题, 我预先给出答案:
- 我开始搞开源的时候还没有GitCafe
- 英语是永恒的壁垒, 突不破这道坎那么你的技术水平有上限, 原因很简单; 新资源几乎总是首先以英语出现, 没有那么多懂技术的翻译和懂翻译的技术, 所以主流的汉语技术资料永恒地落后3到5年并且夹杂大量科学性错误, 教材不用讲了都是上世纪的内容

希望各位能理解我的用意, 谢谢

**Comment by ryanaltair** [comment]
强烈表示赞同 !

发自我的 Windows Phone

---

发件人: Wang Xueruimailto:notifications@github.com
发送时间: ‎2013/‎12/‎17 23:56
收件人: jnrainerds/issue-trackermailto:issue-tracker@noreply.github.com
抄送: wang dongyanmailto:al_tair@live.com
主题: Re: [issue-tracker] 怎么看京东云擎提供的类似github的服务 (#21)

诶对, 为了防止你们问我"为什么有GitCafe这个汉语站还要我们学英语上GitHub"这个问题, 我预先给出答案:
- 我开始搞开源的时候还没有GitCafe
- 英语是永恒的壁垒, 突不破这道坎那么你的技术水平有上限, 原因很简单; 新资源几乎总是首先以英语出现, 没有那么多懂技术的翻译和懂翻译的技术, 所以主流的汉语技术资料永恒地落后3到5年并且夹杂大量科学性错误, 教材不用讲了都是上世纪的内容

希望各位能理解我的用意, 谢谢

---

**Comment by xcodebuild** [comment]
当然不会放弃学习英语的- -，那么这个issue我关了
