### ISSUE TITLE
尝试实现图书扫码软件的iOS客户端

### ISSUE THREAD

**Issue by xulihang** [jnrain/issue-tracker#33]
千辛万苦装了黑苹果，最初目的就是用Xcode。看到itercast网站上的视频教程，感觉ios开发也没有想象中那么难，小软件不需要很多objectc的知识，便试着零基础+搜索来写ios上的图书扫码软件，结果遇到各种险阻。

界面布局还是挺顺利的。遇到storyboard和xib新旧两种格式，没管它们的区别，自动生成的是storyboard。

扫码用第三方的zbar，这里遇到问题。一个是想照搬例子发现错误。半天才知道例子里用了release，而ios5之后采用ARC，自动释放内存，不用release，谁说ios没有碎片化。还有就是模拟器不支持模拟摄像头，测试不了。。于是改用TextEdit手输。

获取json用NSURLRequest，解析json直接用ios sdk自带的NSJSONSerialization。
POST用NSMutableURLRequest。Run一下测试，Android上的功能基本都实现了。

但想装到真的iPhone里还要做很多事。现在打包ipa还不会，上传到appstore要每年99刀的开发者证书，即使是越狱版也要做个假证书。不想再搞了。

![](https://raw2.github.com/xulihang/xulihang.github.io/master/album/ios/1.png)

![](https://raw2.github.com/xulihang/xulihang.github.io/master/album/ios/2.png)

**Comment by xen0n** [comment]
不错。。既然ARC那网络库可以用AFNetworking了，各种意义上都会好一些。话说你这和那两个搞苹果的妹纸不是重了么，可以适当交流下。。。

总之你现在这个应用基本做好就行了。。不要太分散精力

**Comment by xulihang** [comment]
我现在什么都尝试下，什么都不精，只是通过玩技术获得新鲜感。顺便问下论坛以前的linux版版主akira注册听雨的时间比站长晚，但怎么现在在北邮读研了呢？

**Comment by xen0n** [comment]
有新鲜感是好事, 不过也要相对有侧重点, 做我布置的任务对你发展有好处.

注册时间的话不一定非得在大一时候注册吧...

**Comment by xulihang** [comment]
发展方向都不确定，确定就有好处？不过现在新闻记者都在学编程了。对我学英语的，了解点计算机英语是真的。

**Comment by ryanaltair** [comment]
android端也请加油哈，还有就是 ios真的没有碎片化，除了古董ipod iphone，基本上都是ios6和ios7(其中ios7居多)

发自我的 Windows Phone

---

发件人: xulihangmailto:notifications@github.com
发送时间: ‎2014/‎1/‎22 13:32
收件人: jnrainerds/issue-trackermailto:issue-tracker@noreply.github.com
主题: Re: [issue-tracker] 尝试实现图书扫码软件的iOS客户端 (#33)

我现在什么都尝试下，什么都不精，只是通过玩技术获得新鲜感。顺便问下论坛以前的linux版版主akira注册听雨的时间比站长晚，但现在在北邮读研了呢？

---

**Comment by xen0n** [comment]
@xulihang 大多数人的时间不够研究所有的方向, 确定一个方向然后把功夫和时间都用在那上边的话, 会让你在那个方向进步神速, 比如你可以在Android和iOS里边挑一个认真学. 这两个平台同时学的话不光要学2门语言而且设计哲学和应用开发流程工具等等方面的不同会让你疯掉的

**Comment by xulihang** [comment]
知道了。这样看还是写网页一劳永逸，跨平台。我在迷茫的是毕业干什么。。周边人都觉得应该修门会计。
@ryanaltair 额，感觉iOS在不断进步，旧的代码不能很好地适用在新系统上，开发者要与时俱进。这样旧版代码不能直接使用，感觉就是碎片化了。苹果在更新系统和提供支持方面一直做得很好。

**Comment by xen0n** [comment]
好好学技术的话完全可以留在互联网行业的, Python中国社区就好多外语专业的, 美术专业的也有, 所以不用担心. 会计那种专业人太多了, 完全轮不到我们会写程序的去干, 你别觉得你只会写简单的小程序就不算个技术人员了...

**Comment by xen0n** [comment]
@ryanaltair 确认下这个应用的最终使用者有没有苹果平台的需求? 我隐约产生了寒假回来安卓版没法交付的感觉= =

**Comment by ryanaltair** [comment]
没有。

发自我的 Windows Phone

---

发件人: Wang Xueruimailto:notifications@github.com
发送时间: ‎2014/‎1/‎22 17:56
收件人: jnrainerds/issue-trackermailto:issue-tracker@noreply.github.com
抄送: wang dongyanmailto:al_tair@live.com
主题: Re: [issue-tracker] 尝试实现图书扫码软件的iOS客户端 (#33)

@ryanaltair 确认下这个应用的最终使用者有没有苹果平台的需求? 我隐约产生了寒假回来安卓版没法交付的感觉= =

---

**Comment by xen0n** [comment]
嗯好的... 那么@xulihang 项目后端打算怎么搞? 到时候部署在学校机房还是SAE之类的地方? 得早点开始考虑, 开学就要上线了

**Comment by xulihang** [comment]
Android客户端不知道还要加什么功能，做什么完善，感觉已经可以付梓了。
SAE不支持sqlite，在等BAE抢号，折腾半天GAE才发现被墙了。用sqlite的话考虑手机可读取本地数据库。这个放在学校机房应该没什么负担吧？

**Comment by xen0n** [comment]
额. 安卓的事情还是应该回#31 说= =

这个issue如果你不打算有什么后续活动的话可以close了

**Comment by xulihang** [comment]
打扰了，没事就close了。
