### ISSUE TITLE
中文字体授权问题

### ISSUE THREAD

**Issue by xen0n** [jnrain/issue-tracker#4]
@Moyf @soulfere @ryanaltair 你们对制作设计稿时候字体授权这一块怎么看? 英文字体方面好说, 自由授权的一大堆, 但中文的问题就严重了... 听雨的活动分两种性质,
- **非商业部分** 方正的可以随便用, 需要事先和他们的相关部门沟通 (见官网), 其他的不详
- **商业部分** 各大字体厂家对学生的政策均不明, 目测是不能随便用的, 价格**非常高昂**

你们怎么看... 如果有使用需求的话我去发email request方正和造字工房的字体非商业授权了... 需要注意的是我拿到合法授权之后我们就会被记录在案, 不能用上述字体进行商业活动了

**Comment by xen0n** [comment]
如果字体厂子不同意, 我们又没钱买 (admittedly the most probable case) 的话, 商业性质活动的材料就只能用文泉驿字体了2333

说实话用盗版在中国确实很多, 大家也都睁一只眼闭一只眼, 但做大了心里总是过意不去. if only 中文字体大家都可以随便设计...

**Comment by ryanaltair** [comment]
在知乎上看到这个 http://www.zhihu.com/question/19889152
我们用方正的吧 
商用的话 我们作为社团 应该没有商业用途的机会
即使是兼职墙等 
我想我们在那个上面 
他们的给的钱 应该叫做资助更合适吧 
因为 社团没有给任何人发工资
也没有利益的活动 

其实觉得可以用微软的吧 
我只是提议而已（不要吐槽我。）

**Comment by xen0n** [comment]
方正对非营利用途很地道的... 不过前几天看到好几个喜欢的字体是造字工房的, 好贵啊QAQ当然方正客观上还是相当不错的.

微软的话... 有Windows授权就能随便用, 就是不知道2块钱的激活算不算23333 (我2块钱买了个Windows 8激活, 呵了个呵的现在2个月才用一次

**Comment by ryanaltair** [comment]
我的电脑是 那会198优惠更新的 但是 这个会有帮助吗？
现在新电脑基本是标配win8了 正版 

方正地道的 话 我们就选方正吧 毕竟 听雨不商用 这也是原则 （给个广告位应该不算吧）

**Comment by xen0n** [comment]
广告位是很模糊的。。。具体界定我个人认为属于商业性质。。不过一般来讲都是商家自己设计好广告图片吧。。。

那这个问题就先这样吧。。。方正的立场比较清晰，我明天咨询造字工房去了。。closing for now

**Comment by xen0n** [comment]
@ryanaltair @soulfere 造字工房我联系了, 回复非常及时, 他们的字体也可以使用 (需要在较明显位置放置造字工房logo, 这个需求在我打算采用的简洁风格里非常容易实现).

请告知各产品团队设计人员方正和造字工房字体的合法可用性, 请他们去相应官网查阅可用字型, 并 (GitHub上直接或通过你们间接) 告知我决定采用的**具体**字体列表, 我去继续洽谈. 我会尽力确保听雨线上活动的合法性和专业性的.

**Comment by ryanaltair** [comment]
@jnrainerds/promowall-team

**Comment by xen0n** [comment]
因为这个问题现阶段已经不是问题, 再在这个issue里讨论其实不太合适了.

开了新issue, 授权请求和讨论请移步 #6. 本issue结帖, 谢谢
