### ISSUE TITLE
探讨与江南大学青年创业协会合作的可能性

### ISSUE THREAD

**Issue by xen0n** [jnrain/issue-tracker#5]
前两天收到他们组织的邀请, 今天得到了协议, 请各位发表看法.

他们发给我的文档是 doc 格式, 我手工转换成了 Markdown 语法, 内容未作任何改动, 将在下面一一回复给出.

**Comment by xen0n** [comment]
# 社团合作框架协议

甲       方：江南大学青年创业协会
第一 负责人：
联 系 方 式：

乙       方：_____________________
第一 负责人：
联 系 方 式：

## 总则
1. 为促进双方感情交流和合作程度，增加甲乙双方对彼此社团的认识和了解，甲乙双方本着平等合作、互惠互利的原则，根据相关法律法规，经甲乙双方友好协商，制定以下协议，以供双方共同遵守。
2. 本协议需由甲乙双方社团或协会第一负责人签署。
3. 本协议原则时效为一年，实际时效由签署日生效，如有第一负责人换届则本协议暂时终止；协议终止后，若需续签本协议，需新任第一负责人重新签署。
4. 本协议最终解释权归 江南大学青年创业协会 所有。

## 甲方提供支持

为了更好的促进双方协会交流，江南大学青年创业协会（以下称：甲方）自愿对合作社团提供如下支持，旨在做到优秀资源共享，共同学习，共同进步。
1. 社团活动支持
   1. 甲方在收到乙方参与活动的邀请后，将委派代表出席乙方活动或协助活动。
   2. 甲方可提供甲方自有网络平台推广支持，包括但不限于人人网转载、听雨顶贴、微信官方账号发布等协助贵社团宣传。
   3. 甲方可提供线下活动物料支持，包括但不限于长条桌、酒店椅、塑料椅、帐篷、音响、桁架、舞台（如有涉及开支的，由双方具体协商解决）。
   4. 甲方可提供梦想青创青年创业孵化基地咖啡厅作为甲乙双方联谊的活动场所（如有涉及开支的，由双方协商解决）。甲方经梦想青创独家授权赞助。
2. 梦想青创青年筑梦空间支持
   1. 乙方骨干成员（20人以内）每人可获得梦想青创筑梦空间健身房免费使用券每月3张（价值30元/张）。（详见附件：筑梦空间健身房使用规则）
   2. 每月提供一张免费使用券，可免费使用会议室一次。如继续需使用，乙方可获得梦想青创青年筑梦空间会议室使用一次200元的特别优惠（对外800元）；（详见附件：筑梦空间会议室使用规则）
   3. 每学期可免费提供一张免费使用卷。如继续需使用，乙方可获得梦想青创青年筑梦空间活动室使用一次80元的特别优惠（对外500元）。（详见附件：筑梦空间活动室使用规则）
   4. 乙方可获得梦想青创青年筑梦空间所有消费7折优惠。
   5. 乙方成员可优先参与梦想学堂系列讲座（部分名额鉴于讲座规模提供）后免费领取梦想青创筑梦空间健身房免费使用券1张，并有机会获得梦想青创纪念品一份（现场抽取）。
   6. 乙方委派成员在梦想青创常驻办公，办公场所、用电及其他硬件配置均为免费。（详见附件：筑梦空间咖啡厅使用规则）
   7. 乙方可免费使用梦想青创咖啡厅场地进行部门例会（请勿大声喧哗，保持氛围）。
   8. 乙方成员可优先获得甲方提供的兼职信息，以短信通知方式提供。
3. 梦想青创特色活动
   1. 乙方可参与甲方举办的特色活动包括但不限于梦想学堂系列讲座、体育比赛、文艺活动、大型聚会派对。
   2. 乙方可优先获得梦想学堂系列讲座参与邀请（部分名额鉴于讲座规模提供）。
   3. 乙方可与甲方共同参与甲方的活动承办过程，并协助宣传。

## 乙方提供支持

为了更好的提升社团间的合作，尤其社团间相互帮助、相互支持，甲乙双方本着互惠互利的原则拟定本条款，谋求共同发展、共同进步，提升双方认可度。
1. 乙方义务
   1. 乙方需按照甲方相应场地的规定进行活动。
   2. 乙方需保证在使用甲方提供的场地、物料等过程中爱护设施，不破坏。
   3. 在合作过程中，乙方成员应维护江南大学青年创业协会形象和荣誉的行为。
2. 乙方提供支持（部分需乙方自行填写）
   1. 
   2. 
   3. 
   4. 
   5. 
   6. 
   7. 
   8. 
   9. 

## 补充协议
1. 若活动中，甲乙双方任意一方因违反校规校纪造成不好的影响甚至终止活动，一切损失由违规一方承担，并且另一方有权随时终止活动。
2. 本协议由甲乙双方共同协商拟定，未尽事宜如需补充和修改，须经双方共同协商并签署相关补充协议。
3. 若双方合作出现有关包括但不仅限于数量、项目、内容方面的协商，具体信息以最终商议决定的信息为准。

## 其他
1.  如果甲、乙双方在执行此协议时发生争议，甲乙双方应本着友好协商的原则共同协商解决方案。未发生争议的条款继续执行，任何一方不得擅自解除协议。
2.  本协议一式四份，甲、乙双方各执二份，自签订之日起，双方第一负责人签字后生效。
3.  江南大学青年创业协会 战略合作伙伴一览
   共青团无锡市委员会
   共青团无锡市滨湖区委员会
   梦想青创青年创业孵化基地
   无锡市滨湖区青年创业者联盟
   无锡艺南营销策划有限公司
4.  无锡市滨湖区青年创业者座谈会 参会人员名单
   -   共青团系统：
         戴赛平   共青团无锡市委员会基层部副部长
         袁禄来   共青团无锡市滨湖区委员会书记
         石  林    共青团无锡市滨湖区委员会副书记
         邢  鑫    共青团无锡市滨湖区委员会办公室科员
   -   青年创业者代表：
         马  腾    麦梯时尚创意设计有限公司总经理
         许  金    无锡沃华投资顾问有限公司总经理
         李向燕   无锡坦诚物联网科技有限公司（法人）
         沈宏华   瑞莱特精密光电技术无锡有限公司总经理
         张志敏   梦想青创创业公司实体网络部总经理
         张  越    无锡市艺南营销策划有限公司策划经理
         陈艳艳   无锡米勒创意科技有限公司总经理
         林忠鑫   无锡莱特维斯商贸有限公司总经理
         於婷婷   青年筑梦空间网络营销部总经理
         赵  玮    共进青年创业协会会长
         倪岳立   无锡全家网络科技有限公司总经理
         蒋  真    无锡犀点创意设计有限公司总经理

**Comment by xen0n** [comment]
累死了... issue编辑器不是等宽字体...

各位作何感想? @jnrainerds

**Comment by xen0n** [comment]
我感觉这种条件对线下社团还好... 对我们这种网络社团就有点坑了, 你来提供我一台电脑不要装Windows的啊233333 配一套开发环境就够折腾一个下午了还要自己一套他们那里一套什么的233333 内容运营人员宿舍里手机上就能工作非得跑到他们那里233333333

然后我发现好多服务都是给不必要的需求提供优惠... 刺激消费的感觉, 不知道同为创业者为何要如此对待别人, 我对此抱谨慎态度, 拿到协议之前我还以为是很地道的孵化项目呢= =

**Comment by xen0n** [comment]
我靠那边来催我了，各位表个态@soulfere把小伙伴们叫过来

**Comment by soulfere** [comment]
我感觉这个合作没有技术氛围，对方完全是针对线下的俱乐部来搞的这个。甲方优惠条件我唯一看中的在于他的线上扩大宣传面的作用，其他的器材打折什么的没什么吸引力。还有这个我们要拿出什么东西呢？或许我们可以不把条件定的太死，不签协议就不能在网络层面上友好合作么？感觉这样一个合约有一种禁锢的感觉。是不是反而会影响我们的一些行动的自由性。

**Comment by soulfere** [comment]
我觉得我们如果签的话可以把他们打折啊什么的部分适度做降低价值处理，只对应他们有利于我们的项目给出我们自己的优惠就好。

**Comment by xen0n** [comment]
在 2013年11月10日上午11:46，Zhai Qiushi notifications@github.com写道：

> 我感觉这个合作没有技术氛围，对方完全是针对线下的俱乐部来搞的这个。甲方优惠条件我唯一看中的在于他的线上扩大宣传面的作用，其他的器材打折什么的没什么吸引力。还有这个我们要拿出什么东西呢？

只要帮他们宣传他们的活动什么的... 应该就好了吧... 给他们宣传墙一块地方即可

**Comment by soulfere** [comment]
我觉得也好吧，毕竟现在听雨的影响力还是要依靠这些原来就有一定影响力的社团带动。

**Comment by dark-flame-master** [comment]
严格来说－－
这份协议不对等。
感觉像打折促销的会员卡。。。
话说那个健身的跟技术部有关系吗。。。
但是这不是  社团  面对   社团  的协议吗？所以只从我们这些人的角度来考虑就有点不对。
还是听雨俱乐部的事，我觉得没法无视他们的存在，咱们对于线下的东西没兴趣不代表整个社团没有。
对于部长说的禁锢－－
我觉得虽然用词较严重，但性质就是那样。
自行填写的那么多条，就好像对方说：
我们都那么尽力了，你们是不是也表示点诚意啊？！
虽然不排除对方正能量泛滥的可能性，但基本上他是等着咱们积极参加他的活动－－就像回礼一样。

我不赞成听雨举办盛大或者脱离线上的活动，因为那样和听雨的本质就不一样了。而签署这个协议可能不可避免的导致听雨三次元化，而渐渐远离原本的路线。

但是，话说回来，这个的期限是一年，而且和第一负责人挂钩，那么尝试下也未尝不可，可以到期自行结束。

**Comment by xen0n** [comment]
@dark-flame-master 有道理, 必须限制线下活动的参与程度. 我们就算没有这个东西也要广泛地和线下社团开展合作, 而我们用以交换的offering是线上资源, 这样省得他们单养一批技术人员没事干搬砖(!). 所以如果要签的话必须想办法说明白这个互补: 他们提供(出于商业原因有保留的)线下条件, 我们提供(基于人力分配有限的)线上支持

**Comment by xen0n** [comment]
话说这个要签的话应该找高黎他们, 那么你们谁用电子邮件之类的方式direct他来看这里的讨论呢? 得到他的观点之后请原文贴回来, 拜托

**Comment by dark-flame-master** [comment]
@soulfere 感觉人略少......强制把他们叫上来吧

**Comment by xen0n** [comment]
@soulfere 高黎那边进度如何? 把现状同步到这里, 如果决策完毕尘埃落定了这个issue就能close了

**Comment by soulfere** [comment]
二、乙方提供支持（部分需乙方自行填写）
3.2.1 
乙方全力配合甲方在听雨论坛的各类宣传并免收一切费用（如含有商家信息则按照对外报价收取）。
3.2.2
乙方有义务将甲方近期的活动动态反馈在论坛近期活动版块中，不收取任何费用。
3.2.3
乙方可提供自有媒体平台（听雨微信、听雨微博、听雨人人）宣传甲方活动。
3.2.4
乙方可协同甲方合作举办线上或线下的活动。
@xen0n 他们下午去签协议，我特别提示了一下再在合约中加不许卖版的情况。应该可以close issue了。

**Comment by xen0n** [comment]
在 2013-11-14 上午11:48，"Zhai Qiushi" notifications@github.com写道：

> 3.2.4
> 乙方可协同甲方合作举办线上或线下的活动。

诶？！线下？

**Comment by soulfere** [comment]
顺便让他加了一条，如果甲方进行一些存在争议（比较激进），或者是不得到党宣支持（甚至反对）的活动，乙方有权不参与宣传。应该这样会稳妥一点。

**Comment by soulfere** [comment]
线下应该也会有吧，毕竟俱乐部的人要干活。可能是派人出席一些他们的活动什么的。

**Comment by xen0n** [comment]
不定义清楚“协同”的范畴吗？需要限制我们的参与程度我觉得

**Comment by xen0n** [comment]
还有“全力”改成“尽力”，万一他们对我们不满意我们才有台阶下，全力的话就无底洞了

**Comment by soulfere** [comment]
恩恩，刚才问了一下高黎，他说今天下午是初步沟通交流了一下，我把你上面的话转达给他了。
