### ISSUE TITLE
听雨俱乐部 技术部  直属线上管理 的建议

### ISSUE THREAD

**Issue by ryanaltair** [jnrain/issue-tracker#7]
@xen0n 这个问题我一直在考虑 关于 听雨技术部的体制改革 
# 现状

大一升到大二
 大部分人退出 
少部分 以部长或者副部等身份留在技术部

现状直接导致的结果
第二年招新完后 
大部分大一不能完成网站（或者后端）开发的任务
 而大二的由于基本身兼数职 也基本不能进行 网页等开发工作 
# ryanaltair的改革思路：
## 1.听雨研发中心概述

技术部直接并入线上的听雨研发中心直管 
听雨研发中心设总负责人 副负责人2名（职称待定）
项目负责人多名（职称待定）
开发者多名
其中 开发者仅对项目负责人负责 
项目负责人仅对总，副负责人负责
总负责人由站长兼任
副负责人1由副站兼任
副负责人2由大二级担任
## 2.技术部与俱乐部的关系 

在线下俱乐部挂名 由线上站长兼容总负责人（是否挂名及方式待定，需与老师商量）
听雨俱乐部活动 对听雨研发中心成员不做强制参加要求
听雨俱乐部中层会议 要求 听雨研发中心 副负责人2 必须参加 （如有特殊情况 需由总负责人或副负责人1代为参加）
一切俱乐部活动 
除非需要
专门制作网页宣传页面
活动辅助页面 
投票页面等 
才分配任务给江南听雨研发中心 （此时中心可以协商 但不可拒绝 ）
任务由中心副负责人联系 由大二级开发者（项目负责人）接手 带领大一级新干事进行开发
这样做 即可相当程度上避免技术断层的存在（理论上）
## 3.技术部人员流向

大一升大二时 不做退部要求（因为技术部直属听雨研发中心） 也不做任何部门调离安排 
大二（甚至大三）时候仍旧留在技术部(听雨研发中心）
.即 加入后的任期是 4年制（至少是2年制）
## 4.常规情况下

对外宣传为 听雨研发中心
## 5.招新

 仍旧按现行方式 在听雨招新时对大一进行集中面试与招新 
对其他年级也做常年招新（需要进行2次考核）
部长的选拔 从上一年大一干事中选取 此后 该部长专门（仅）负责与线下联系 
而其他大一的在升为大二后 
作为技术开发项目负责人 单独对站长负责 大一新生在进入技术部后 双向选择大二部长作为开发指导人 并由该指导负责任务分配

**Comment by xen0n** [comment]
我现在要出学校... 等回来仔细看

**Comment by xen0n** [comment]
-   **关于取消技术部**
  
  这个我学期初的时候问过指导老师和高黎, 他们的意思是不同意大的组织结构变动. 就是说给已有的组织和职位换个名字都不行... 所以你的这份提议以原样目测是过不去其他高层的.
-  **解决方法**
  
  个人认为既兼容线下既有组织结构, 又避免主力技术人员精力分散的办法, 莫过于让技术部回归当初成立时的最初目的 -- **为线上输送技术人才**. 就是说面试和培训都以技术部名义进行, 但经过培训认为合格的成员**吸收进线上研发中心, 自动退出技术部**, 于是成功实现了线下附属部门的改头换面. 这个经验同样适用于其他部门, 于是渐进地可以将线下线上分裂的局面收拾清楚 (并不是完全解决, 但以现在领导层的改革意愿来看完全解决短期内应该是不可能的).

**Comment by xen0n** [comment]
这个我跟 @soulfere 今天中午偶然碰面也聊了... 你觉得如何? @soulfere 也来说说看法呗...

**Comment by ryanaltair** [comment]
高黎方面
前天和高黎聊过 他的意见是 不反对 
因为技术部在线下确实位置比较尴尬 
而转移到线上直属的话 会更利于技术部发挥能效

知道老师方面：
他比较希望 听雨能够进行长期有效的技术开发 
我认为 这方面 他的意见不会是反对 
技术部人才流失现象严重的问题他也有了解到 
他也想改变这个现状

**Comment by ryanaltair** [comment]
关于领导层对于 现有体系的改变 
在这个学期内 可能难以实现有效的改变 
但是 高黎 和我 都认为 现在这样的体系弊端很大 
有必要重新调整 为了更灵活的发展

**Comment by ryanaltair** [comment]
这方面 我想我能代表高层的意见 如果这样的架构重整能够减少技术部人才流失的话 
我愿意 为此 与老师 详谈（以 前技术部干事和主席助理的身份）

**Comment by xen0n** [comment]
态度软化了吗... 我表示怀疑... 一步一步来总是没错的

我觉得把技术人员的招募和培训全部拉到线上而其他部门没有跟着聚集到线上的话, 那会形成更严重的信息不对称...
- GitHub vs QQ
- Markdown vs Micro$oft Word
- 帖子 vs 短信
- 诸如此类

更何况还有刷人的问题... 新人需要一步一步地成长, 而显然不是所有新人都能成长到胜任研发的程度. 那么让他们呆在技术部可能会比被研发中心歧视要感觉好受一点, 毕竟不是同一群人.

于是我开始怀疑他们现在突然转变想法是想把硬骨头随便丢给我们啃...

**Comment by xen0n** [comment]
减少人才流失的根本方法是维持他们的兴趣和热度... 就是我们得多做事情多闹动静, 维持存在感. 加上开放的人事组织结构, 就算有人走了他发现这里又出来一个有趣的项目他也会回来的. 在这方面多想想也许有效果...

**Comment by ryanaltair** [comment]
这个想法是我提出的
他们不会有 这种恶意  他们现在突然转变想法是想把硬骨头随便丢给我们啃
这点请放心
在下 认为纯粹的技术上优越感不能作为歧视的理由 本身这种歧视感存在 对社团的健康成长也是有害无益
正如 3D打印从业人员 根本没有理由 怀疑（或者看不起）  数控机床加工零件技术

**Comment by soulfere** [comment]
@xen0n 你上面的观点还是挺有道理的 @ryanaltair 我觉得这个某种程度上不是他们同意不同意的问题，大道理谁都知道，可是我们也要考虑即使他们同意，我们有没有具体的对策来完美的完成这个转变，你说的技术部到线上流失的问题，取消技术部或者说技术部线上化同样得不到解决，如上，根本问题在于兴趣，不在于形式。要有吸引他们留下来的东西。而且相比线下有纸有字，自由开发的线上的组织结构更不牢靠，很有可能让别人觉得这个组织更不靠谱。你要知道，对大一的以这样的线上组织来招新，就我们学校这种偏文的性质，是找不到新人的。而且大一学生加入社团本来就出于一部分兴趣，一部分交际，线上完全剥离了三次元正常的交际圈，鲜会有人去理会这样的组织的。也就是说，这样做虽然有好处，可是坏处并不小。

**Comment by ryanaltair** [comment]
指导老师那边的想法 其实 就是 想要 复制 华中科技的冰岩 模式 
那么 现在 仅 听雨现在软件开发中心的人数 上来看 显然 把大一的并入技术部 
也是值得的 至于多做事情 和多闹动静 这一点 我认为 即使这一届大一部分人技术上不够给力
但是 做下指导 也是足够的

**Comment by soulfere** [comment]
现在技术部做的是找苗子，去把他们对技术的好奇转变成对技术的热爱，以至于能对技术投入自己的心血来做项目。矛盾在于人才流失，不全在于结构，你说技术部觉得闲没事干，是因为他们线上也没事干。还是要在给他们事情做上下功夫，最好让他们的任务也循序渐进。

**Comment by xen0n** [comment]
你看看你看看... 江大他尼玛不是纯理工科院校啊! 咱没有人家的相对优质生源, 没有人家的深厚工程传统, 没有人家的理工科气息的沉淀, 有的只是艺术和商业这些realistic到可怕的东西. 江大作为这么一个完全没有IT底子的学校, 照搬别人的技术发展模式只能是死亡, 像BBS技站这种完全复制其他各大BBS的东西你仔细看看就会发现像我这种C/PHP/前端/运维通吃的江大你找不出来的 (惨痛的事实, 非自夸, 要能有第二个我会非常欣慰的并立即撤回这句话)...

啥? 你说其他一些非理工科学校的论坛也风生水起? 于是他们页面底部清一色的Discuz... 呕...

我还是觉得照搬这种做法有点病急乱投医的感觉了... 现在我只是想快点形成我们线上研发中心的实体, 并且我这里加紧开发新站, 这样大家都有事情做, 问题才能解决

**Comment by xen0n** [comment]
@soulfere 嗯, 所以我在前几天给4个企划团队也传达了必须有线上站点的意思. 最后加起来就会有不少具有挑战性的任务, 而每个基本上都是简单的数据库操作, 于是成员有了接触并练习从未接触过的新奇玩意儿的机会, 好奇心才能起来

**Comment by ryanaltair** [comment]
他们的意思 是想要达成那种效果 达成那种 技术流传的效果
现在 技术部的情况 
2011级别 无人留下 
2012级别 翟秋实 我 
2013级别 如果继续这个趋势 那么 应当是4个人

**Comment by soulfere** [comment]
@ryanaltair 这样不是递增了么，技术资源是靠积累的，不是一口吃成一个胖子的，一步一步来吧。

**Comment by ryanaltair** [comment]
本话题先暂告一段落

**Comment by ryanaltair** [comment]
鉴于时间原因 我直接在把1楼的修改了
